version: 1.0
app:
  # build id to deploy
  # version: 1.0-SNAPSHOT-20230716015630
  # number of instances
  instances:
    # min number of instances. can be 0 for scale to 0. default to 1.
    min: 1
    # max number of instances. defaults to 1 if min == 0, otherwise defaults to min
    # q: what's the overall limit?
    max: 2
  resources:
    # max cpu, defaults to 1 cpu limit, half of that for min, min >= 1
    # q: what's the overall limit?
    # q: do we support fractions?
    cpu: 1
    # memory limit is based on cpu value: 1:3 memory ratio, e.g. 1 cpu == 3 gb
    # ephemeral disk limit will be set to 1GB  
  # List of environment variables that set for the application
  # Liberty encrypted values are supported only if referenced in server.xml
  env:
    - name: JVM_ARGS # q: make that as a top level 'jvmArguments' property?
      value: "-DenvironmentType=stage"
    - name: MY_ENV
      value: "1"
    - name: DBHost
      value: "ec2-35-153-18-9.compute-1.amazonaws.com"
    - name: DBName
      value: STSECDB
    - name: DBPort
      value: "50000"
    - name: DBUser
      value: db2inst1
    - name: DBPass
      value: "{xor}Oz1tLz4sLChvLTs="
    - name: sslconn
      value: "false"
  # List of variables that can be referenced in server.xml
  # Liberty encrypted values are supported
  variables:
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
  version: "e1f7c858-5676-4a6c-8ca8-0859d2584fb9"
  # Set the Java runtime version since sometimes (usually) the pom.xml compiler settings are 1.8
  java: 17
